yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace="posts")),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        db_index=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Загрузите картинку',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='no_self_follow'
            ),
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following'
            )
        ]

    def __str__(self):
        return f'Подписка {self.user} на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']

        if not data:
            raise forms.ValidationError(
                'Пост не должен быть пустым!',
            )
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        data = self.cleaned_data['text']

        if not data:
            raise forms.ValidationError(
                'Комментарий не должен быть пустым!',
            )
        return data

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()

SHOW_POSTS = 10


def index(request):
    template = 'posts/index.html'
    posts_all = Post.objects.all()

    paginator = Paginator(posts_all, SHOW_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts_all = group.posts.all()

    paginator = Paginator(posts_all, SHOW_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts_all = author.posts.all()
    posts_count = author.posts.count()
    following = False

    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists()

    paginator = Paginator(posts_all, SHOW_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'author': author,
        'posts_count': posts_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    form = CommentForm()
    comments = post.comments.all()

    context = {
        'post': post,
        'posts_count': posts_count,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )

    if request.method == 'POST':

        if form.is_valid():
            post_temp = form.save(commit=False)
            post_temp.author = request.user
            post_temp.save()
            return redirect('posts:profile', username=request.user.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect('/posts/' + str(post_id))

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if request.method == 'POST':

        if form.is_valid():
            form.save()
            return redirect('/posts/' + str(post_id))

    return render(request, 'posts/create_post.html', {
        'form': form,
        'post_id': post_id,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment_temp = form.save(commit=False)
        comment_temp.author = request.user
        comment_temp.post = post
        comment_temp.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'

    fav_posts = Post.objects.filter(author__following__user=request.user)

    paginator = Paginator(fav_posts, SHOW_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)

    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)

    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if form.instance.id %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}  
{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if form.instance.id %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}             
          </div>
          <div class="card-body">

            {% include 'includes/show_errors.html' %}

            <form method="post" enctype="multipart/form-data"
              action="
                {% if form.instance.id %}
                  {% url 'posts:post_edit' post_id=post_id %}
                {% else %}
                  {% url 'posts:post_create' %}
                {% endif %}
              "
            >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if form.instance.id %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления избранных авторов{% endblock %}


  {% block content %}
    <div class="container py-5">

      <h1>Последние обновления избранных авторов</h1>
      {% include 'posts/includes/switcher.html' %}
        {% cache 20 follow_page request.GET %}
          {% for post in page_obj %}
            {% include 'posts/includes/single_post.html' %}

            {% if post.group %}
              <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
                Все записи группы
              </a>
            {% endif %}

            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        {% endcache %}
      {% include 'posts/includes/paginator.html' %}

    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Записи сообщества {{ group }}
{% endblock %}

{% block content %}
  <div class="container py-5">

    {% for post in page_obj %}
      {% if forloop.first %}
        <h1>{{ post.group }}</h1>
        <p>{{ post.group.description}} </p>
      {% endif %}
      {% include 'posts/includes/single_post.html' %}

      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}

    <a href="{% url 'posts:index' %}">На главную</a>

  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}


  {% block content %}
    <div class="container py-5">

      <h1>Последние обновления на сайте</h1>
      {% include 'posts/includes/switcher.html' %}
        {% cache 20 index_page request.GET %}
          {% for post in page_obj %}
            {% include 'posts/includes/single_post.html' %}

            {% if post.group %}
              <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
                Все записи группы
              </a>
            {% endif %}

            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        {% endcache %}
      {% include 'posts/includes/paginator.html' %}

    </div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Пост {{ post|truncatechars:31 }}
{% endblock %}

{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
          <li class="list-group-item">
            Группа:
            {% if post.group %} 
              {{ post.group }}<br>
              <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
                Все записи группы
              </a>
            {% else %} Группа не указана
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' username=post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>

      {% if post.author.username == user.username %}
        <a href="{% url 'posts:post_edit' post_id=post.pk %}">
          Редактировать пост
        </a>
      {% endif %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">

            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group mb-2">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                  </label>
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>

          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
              <p>
              {{ comment.text|linebreaksbr }}
              </p>
            </div>
          </div>
      {% endfor %}      

    </article>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
  <div class="container py-5">

    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ posts_count }} </h3>
      {% if user.is_authenticated and author != user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}  
    </div>

    {% for post in page_obj %}
    {% include 'posts/includes/single_post.html' %}

    {% if post.group %}
      <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
        Все записи группы
      </a>
    {% endif %}

    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
    <br>
    <a href="{% url 'posts:index' %}">На главную</a>
    
  </div>
{% endblock %}